# Generated by Django 6.0.3 on 2026-03-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockquestion',
            name='level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
