# Generated by Django 6.0.3 on 2026-03-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mock_interview', '0002_mockquestion_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocksession',
            name='time_per_question',
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name='mocksession',
            name='voice_id',
            field=models.CharField(default='MmiGAbOYCaIFzgNItUWa', max_length=100),
        ),
    ]
